#!/usr/bin/env bash
# Install the SimpleCLI tool

cd $(dirname "${BASH_SOURCE[0]}") || exit 1
DIR="$(pwd)"
INSTALLDIR="/usr/local"

function install() {
  mkdir -p "${INSTALLDIR}/bin"

  rm -fr "${INSTALLDIR}/lib/simplecli"
  mkdir -p "${INSTALLDIR}/lib/simplecli"

  rsync -azh "${DIR}/bin/" "${INSTALLDIR}/bin/"
  rsync -azh "${DIR}/lib/" "${INSTALLDIR}/lib/simplecli/"

  cd /usr/local/bin || exit 1
  chmod +x appify  cli  con  headerchk  mbox2imap  slacktee  ssllabs-scan-v3 thycotic_sshproxy

  sudo -H pip3 --quiet install pexpect requests certifi

  if [[ -d "${DIR}/.git" ]]
  then
    rsync -azh "${DIR}/.git" "${INSTALLDIR}/lib/simplecli/"
  fi

  echo "SimpleCLI successfully installed"
}

install
