#!/usr/bin/env bash
# Install the SimpleCLI tool

cd $(dirname "${BASH_SOURCE[0]}") || return 1
DIR="$(pwd)"
INSTALLDIR="/usr/local"

function install() {
  mkdir -p "${INSTALLDIR}/bin"

  rm -fr "${INSTALLDIR}/lib/simplecli"
  mkdir -p "${INSTALLDIR}/lib/simplecli"

  rsync -azh "${DIR}/bin/" "${INSTALLDIR}/bin/"
  rsync -azh "${DIR}/lib/" "${INSTALLDIR}/lib/simplecli/"

  cd /usr/local/bin || return 1
  chmod +x appify  cli  con  *headerchk  mbox2imap  slacktee  ssllabs-scan-v3 thycotic_sshproxy

  sudo -H pip3 --quiet install pexpect requests certifi

  if [[ -d "${DIR}/.git" ]]
  then
    rsync -azh "${DIR}/.git" "${INSTALLDIR}/lib/simplecli/"
  fi

  echo "SimpleCLI successfully installed"
}

function link_bashy(){
  which -a npm > /dev/null || echo -e "\n!!! npm not found, please install NPM or update your PATH"
  cd /usr/local/lib/simplecli/bashy || echo -e "\n!!! bashy not available, please update SimpleCLI"

  npm link > /dev/null
  echo -e "BASHY successfully installed"
}

reset
echo ""

if [[ ! "$(uname -s)" == "Darwin" ]]
then
  echo -e "\nThis is macOS specific CLI; some things will work fine others won't."
  echo -e "Install will continue but you have been warned... \[._.]/"
  echo -en "\nPress enter key to continue."
  read
  reset
fi
install
link_bashy

echo -e "\n!!! Please add the following to your .bash_profile, or equivalent to use SimpleCLI:"
echo 'source "/usr/local/lib/simplecli/bash/common"'

echo -e "\n!!! If you would like to use included 1password cli functions then add the following as well:"
echo 'source "/usr/local/lib/simplecli/bash/1passwd-cli"'

echo -e "\nA very basic Homebrew bootstrap is available via: 'cli brew bootstrap'"
source "${HOME}/.bash_profile"
echo ""

