#!/usr/bin/env bash
# 1password-cli functions

function opon(){
  source "${LOGIN_TRACKER}"
  if [ $(( ${OP_SESSION_LIFETIME} - $(date +%s) )) -lt 30 ]
  then
    eval $(op signin my)
    export OP_SESSION_LIFETIME="$(date +%s -d '+30 minutes')"
    {
      echo -e "export OP_SESSION_my=${OP_SESSION_my}"
      echo -e "export OP_SESSION_LIFETIME=${OP_SESSION_LIFETIME}"
    } > "${LOGIN_TRACKER}"
    source "${LOGIN_TRACKER}"
  fi
}

function opoff(){
  op signout
  unset OP_SESSION_my
  unset OP_SESSION_LIFETIME
  rm -f "${LOGIN_TRACKER}"
  touch "${LOGIN_TRACKER}"
}

function listkeys(){
  opon
  op list items --categories "Secure Note" "$1" --vault "$2" | op get item - --fields title | grep -i "ssh-key"
}

function getsshkey(){
  opon
  op get item --fields notesplain "$1" --vault "$2" | base64 -d
}

function addsshkey(){
  opon
  getsshkey "$1" "$2" | ssh-add -q -
}

function getsshkey.pub(){
  local OUTPUT=$(mktemp)
  opon
  getsshkey "$1" "$2" > "${OUTPUT}"
  chmod 600 "${OUTPUT}"
  ssh-keygen -y -f "${OUTPUT}"
  rm -f "${OUTPUT}"
}

function getpwd(){
  opon
  op get item --fields password "$1"  --vault "$2" | pbcopy -Prefer txt
}

function getuser(){
  opon
  op get item --fields username "$1" --vault "$2"
}

function gettoken(){
  opon
  op get item --fields "Personal Access Token" "$1" --vault "$2"
}

function getmfa(){
  opon
  op get totp "$1" --vault "$2" | pbcopy -Prefer txt
}

function update_op(){
  opoff
  cd "/tmp" || exit 1
  rm -f op_darwin*
  wget $(lynx -dump -listonly https://app-updates.agilebits.com/product_history/CLI \
    | grep ^"\ \ \ 2" \
    | sed -r 's/^\ \ \ [0-9]+\. //')
  sudo installer -pkg $(ls op_darwin_amd64*) -target /
}