#!/usr/bin/env bash
# 1password-cli functions

function opon(){
  source "${LOGIN_TRACKER}"
  if [ $(( ${OP_SESSION_LIFETIME} - $(date +%s) )) -lt 30 ]
  then
    eval $(op signin my)
    export OP_SESSION_LIFETIME="$(date +%s -d '+30 minutes')"
    {
      echo -e "export OP_SESSION_my=${OP_SESSION_my}"
      echo -e "export OP_SESSION_LIFETIME=${OP_SESSION_LIFETIME}"
    } > "${LOGIN_TRACKER}"
    source "${LOGIN_TRACKER}"
  fi
}

function opoff(){
  op signout
  unset OP_SESSION_my
  unset OP_SESSION_LIFETIME
  rm -f "${LOGIN_TRACKER}"
}

function listkeys(){
  opon
  op list items | jq -r | grep -i ssh-key | awk -F\: '{print $2}'
}

function addsshkey(){
  opon
  op get item --fields notes "$1" | ssh-add -q -
}

function getsshkey(){
  opon
  op get item --fields notes "$1"
}

function getsshkey.pub(){
  opon
  op get item --fields notes "$1" > "/tmp/keytmp"
  chmod 600 "/tmp/keytmp"
  ssh-keygen -f "/tmp/keytmp" -y
  rm -f "/tmp/keytmp"
}

function getpwd(){
  opon
  op get item --fields password "$1" | pbcopy -Prefer txt
}

function getuser(){
  opon
  op get item --fields username "$1"
}

function gettoken(){
  op get item "$1" | jq -r '.details.sections[] | select(.fields).fields[] | select(.t== "Personal Access Token").v'
}

function getmfa(){
  opon
  op get totp "$1" | pbcopy -Prefer txt
}

function update_op(){
  opoff
  cd "/tmp" || exit 1
  rm -f op_darwin*
  wget $(lynx -dump -listonly https://app-updates.agilebits.com/product_history/CLI \
    | grep ^"\ \ \ 2" \
    | sed -r 's/^\ \ \ [0-9]+\. //')
  sudo installer -pkg $(ls op_darwin_amd64*) -target /
}
