#!/usr/bin/env bash
# Wrapper for Homebrew on MacOS

function brew_description(){
    echo "Homebrew toolchain for macOS"
}

function brew_help(){
  echo -e "\n usage: $(basename "$0") homebrew <subcommand>"
  echo -e "\n AVAILABLE SUBCOMMANDS:\n"
  echo " bootstrap   install Homebrew with a base set of options and tools"
  echo " fix         attempt to fix anything that has gone wrong"
  echo " remove      remove Homebrew from the system"
  echo " meaint      perform Homebrew maintenance"
  echo " multi       attempt to make Homebrew multiuser"
  echo " help        this message"
	echo ""
}

function brew_handle(){
  command="$1"

  case $command in
    bootstrap)
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      xargs brew install < "${CLIHOME}/brew_bootstrap_packages"
    ;;

    remove)
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
    ;;

    maint)
      command -v brew || exit 1
      brew update --quiet
      brew upgrade --quiet
      brew doctor
      brew missing
      brew cleanup -s
    ;;

    multi)
      echo -e "\nYou will need to add users to the group 'admin'."
      sudo chgrp -R admin $(brew --prefix) $(brew --prefix)/Cellar
      sudo chmod -R g+rwX $(brew --prefix) $(brew --prefix)/Cellar
    ;;

    help)
      brew_help
    ;;

    *)
      brew_help
    ;;
  esac
}
