#!/usr/bin/env bash
# Wrapper for Homebrew on MacOS

function brew_description(){
    echo "Homebrew toolchain for macOS"
}

function brew_help(){
  echo -e "\n usage: $(basename "$0") homebrew <subcommand>"
  echo -e "\n AVAILABLE SUBCOMMANDS:\n"
  echo " bootstrap   Install Homebrew with a base set of options and tools"
  echo " fix         Attempt to fix anything that has gone wrong"
  echo " remove      Remove Homebrew from the system"
  echo " update      Update and cleanup the Homebrew installation"
  echo " multiuser   Attempt to make Homebrew multiuser"
	echo ""
}

function brew_handle(){
  command="$1"

  case $command in
  bootstrap)
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install findutils --with-default-names
    brew install gnu-indent --with-default-names
    brew install gnu-sed --with-default-names
    brew install gnutls --with-default-names
    brew install gnu-tar --with-default-names
    brew install gawk --with-default-names
    brew install coreutils --with-default-names
    brew install wget
    brew install terminal-notifier
    brew install popt
    brew install boost
    brew install bash-completion
    brew install shellcheck
    brew install lesspipe
    brew install jq
    brew install shfmt
    brew install golang
    brew cask install android-sdk
    brew cask install android-platform-tools
    brew cask install java
  ;;

  fix)
    pushd +0 . || exit 1
    cd /usr/local || exit 1
    git remote add origin git://github.com/mxcl/homebrew.git
    git fetch origin
    git reset --hard origin/master
    brew update
    popd || exit 1
  ;;

  remove)
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
  ;;

  update)
    brew update
    brew upgrade
    brew cleanup
    brew doctor
  ;;

  multiuser)
    echo -e "\nYou will need to add users to the group 'admin'"
    sudo chgrp -R admin /usr/local/*
    sudo chmod -R g+w /usr/local/*
    sudo chgrp -R admin /Library/Caches/Homebrew
    sudo chmod -R g+w /Library/Caches/Homebrew
    sudo chgrp -R admin /opt
    sudo chmod -R g+w /opt
    brew doctor
  ;;

	*)
		brew_help
	;;
  esac
}
