#!/usr/bin/env bash
# Simple MacOS cleanup toolchain

function clean_description(){
    echo "cleanup macOS system cruft"
}

function clean_help(){
  echo -e "\n usage: $(basename "$0") clean <subcommand>"
  echo -e "\n AVAILABLE SUBCOMMANDS:\n"
  echo " all         full clean"
  echo " tm          remove TimeMachine local snapshots"
  echo " ql          remove QuickLook cache"
  echo " dns         remove DNS cache, if possible"
  echo " mem         purge unused pages and return them to free pool"
  echo " xauth       reset the Xauth control file"
  echo " help        this message"
  echo ""
}

function clean_timemachine(){
  #TimeMachine local snapshots
  for s in $(tmutil listlocalsnapshots / | awk -F\. '{print $4}')
    do
      sudo tmutil deletelocalsnapshots $s
  done
}

function clean_syscache(){
  #system caches
  sudo rm -rf "/Library/Caches/*" > /dev/null 2>&1

  #application caches
  rm -rf "${HOME}/Library/Containers/*/Data/Library/Caches/*" > /dev/null 2>&1
}

function clean_quicklook(){
  #quicklook purge
  qlmanage -r > /dev/null 2>&1
  qlmanage -r cache > /dev/null 2>&1
  rm -f "${HOME}/Library/Preferences/com.apple.quicklookconfig.plist" "${HOME}/Library/Preferences/com.apple.QuickLookDaemon.plist"
  sudo killall cfprefsd >/dev/null 2>&1
}

function clean_logs(){
  #user logs
  sudo rm -rf "${HOME}/Library/logs/*" > /dev/null 2>&1

  #system logs
  sudo rm -rf "/Library/logs/*" "/var/log/*" "/private/var/folders/*" > /dev/null 2>&1
}

function clean_xauth(){
  command -v xauth || exit 1
  local host key
  host="$(hostname)"
  key="$(perl -e 'srand; printf int(rand(100000000000000000))')"
  key="$key$key"
  /usr/X11/bin/xauth list | awk '{print $1}' | xargs /usr/X11/bin/xauth remove
  /usr/X11/bin/xauth add "${host}"/unix:0 . "$key"
}

function clean_handle(){
  command="$1"

  case $command in
  all)
    sudo killall -HUP mDNSResponder
    clean_timemachine
    clean_syscache
    clean_quicklook
    clean_logs
    clean_xauth
    echo ""
  ;;

  tm)
    clean_timemachine
  ;;

  ql)
    clean_quicklook
  ;;

  dns)
    sudo killall -HUP mDNSResponder
  ;;

  mem)
    sudo purge
  ;;

  xauth)
    clean_xauth
  ;;

  help)
    clean_help
  ;;

  *)
    clean_help
  ;;

   esac
}
