#!/usr/bin/env bash
# Wrapper for some Git functions

function gh_description(){
  echo "GitHub API helpers."
}

function gh_help(){
  echo -e "\n usage: $(basename "$0") gh <subcommand>"
  echo -e "\n AVAILABLE SUBCOMMANDS:\n"
  echo " push-keys        push ssh-keys from 1password-cli"
  echo " list-keys        list current ssh-keys for user in format <keyid> <title>"
  echo " del-key          delete ssh-key by key id; use list-keys to get key id"
  echo " help             this message"
  echo ""
}

function gh_handle(){
  # This function expects go find your Github credentials stored in 1password under an item
  # titled Github; if it can't be found it fail.

  local MERGED_BRANCHES="/tmp/cli-git-mb.txt"
  local OUTPUT=$(mktemp)
  local GHUSER=$(getuser github)
  local GHTOKEN=$(gettoken github)
  command="$1"

  case $command in
    push-keys)
      shift;
      getsshkey.pub $2 > ${OUTPUT}
      curl -s -u "${GHUSER}:${GHTOKEN}" \
      -X POST \
      -H "Accept: application/vnd.github.v3+json" \
      -d '{"title":"'$1'","key":"'"$(cat ${OUTPUT})"'"}' \
      https://api.github.com/user/keys
    ;;

    list-keys)
      curl -s -u $(getuser github):$(gettoken github) \
      -X GET \
      -H "Accept: application/vnd.github.v3+json" \
      https://api.github.com/user/keys | jq -r '.[] | "\(.id) \(.title)"'
    ;;

    del-key)
      shift;
      curl -u "${GHUSER}:${GHTOKEN}" \
      -X DELETE \
      -H "Accept: application/vnd.github.v3+json" \
      https://api.github.com/user/keys/$1    
    ;;

    help)
      gh_help
    ;;

    *)
      gh_help
    ;;
  esac
}
