#!/usr/bin/env bash

function ip_description(){
    echo "Get and/or validate IPv4 addresses."
}

function ip_help(){
  echo -e "\n usage: $(basename "$0") ip <subcommand>"
  echo -e "\n AVAILABLE SUBCOMMANDS:\n"
  echo " external     Get the visible external IPv4 Address"
  echo " local        Get the local device and IPv4 Address"
  echo " validate     Confirm a string 'looks' like an IPv4 Address"
  echo ""
}

function ip_handle(){
  command="$1"

  case $command in
  external)
    exip="$(curl -s 'https://api.ipify.org?format=text')"
    echo ""
    echo -e "\nExternal visible IPv4 Address: ${exip}\n"
    echo ""
  ;;

  local)
    echo ""
    echo -e "Local IPv4 addresses:"
    ifconfig | grep -iw 'inet' | grep -Ev '127.0.0.1|::1' | awk '{print $2}'
    echo ""
    echo -e "Local IPv6 addresses:"
    ifconfig | grep -iw 'inet6' | grep -Ev '127.0.0.1|::1' | awk '{print $2}'
    echo ""
  ;;

  validate)
    shift;
    ip="$1"

    if [[ ! $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo ""
      echo "$ip: does not appear to be a valid dotted quad."
      echo ""
    fi
  ;;

  *)
    ip_help
  ;;

  esac
}
