#!/usr/bin/env bash
# Wrapper for some Git functions

function jekyll_description(){
  echo "Jekyll website 'wrapper' for some often used features."
}

function jekyll_help(){
  echo -e "\n usage: $(basename "$0") git <subcommand>"
  echo -e "\n AVAILABLE SUBCOMMANDS:\n"
  echo " Requires BLOG_HOME to be set for use as [directory]"
  echo " serve             run a local instance out of [directory]"
  echo " stop              stop all running jekyll processes"
  echo " publish           commit and push to Github Pages"
  echo " status            output current pid and curl output to baseurl"
  echo " post              make a new post in the _posts [directory]"
  echo " page              make a new page in the _pages [directory]"
  echo ""
}

function jekyll_post(){
  local POST_DATE="$(date +'%Y-%m-%d %H:%M:%S %z')"
  local POST_TITLE
  local POST_SUBTITLE

  echo -e "\nWhat is the title of your new post?"
  read -r POST_TITLE

  echo -e "\nWhat is the subtitle of your new post?"
  read -r POST_SUBTITLE

cat <<EOF > "_posts/$(date +'%Y-%m-%d')-${POST_TITLE}.md"
---
layout: post
title: $POST_TITLE
subtitle: $POST_SUBTITLE
date: $POST_DATE
gh-repo: $JEKYLL_GH_PROMO
gh-badge: [star, fork, follow]
tags: [post]
comments: true
---
EOF
}

function jekyll_page(){
  local PAGE_DATE="$(date +'%Y-%m-%d %H:%M:%S %z')"
  local PAGE_TITLE
  local PAGE_SUBTITLE

  echo -e "\nWhat is the title of your new post?"
  read -r PAGE_TITLE

  echo -e "\nWhat is the subtitle of your new post?"
  read -r PAGE_SUBTITLE

  echo -e "\nWhat do you want the use as the permalink?"
  read -r PAGE_PERMALINK

cat <<EOF > "_pages/$(date +'%Y-%m-%d')-${PAGE_TITLE}.md"
---
layout: page
permalink: "/$PAGE_PERMALINK/"
title: $PAGE_TITLE
subtitle: $PAGE_SUBTITLE
date: $PAGE_DATE
gh-repo: $JEKYLL_GH_PROMO
gh-badge: [star, fork, follow]
tags: [page]
comments: true
---
EOF
}

function jekyll_handle(){
  if [ ! -x "$(which jekyll)" ]
  then
    sudo gem install -n /usr/local/bin jekyll
  fi

  if [ ! -x "$(which pidof)" ]
  then
    brew install pidof
  fi

  command="$1"

  case $command in
    serve)
      bundle exec jekyll serve --livereload > "/tmp/jekyll_serve.log" 2>&1 &
      echo "Sleeping 5s to complete startup..." && sleep 5
      cat "/tmp/jekyll_serve.log"
      echo ""
    ;;

    stop)
      pgrep -f jekyll | xargs kill -9 > /dev/null 2>&1
    ;;

    post)
      git checkout master
      git pull
      jekyll_post
    ;;

    page)
      git checkout master
      git pull
      jekyll_page
    ;;

    status)
      echo -e "\nJekyll pid: $(pgrep -f jekyll)\n"
      curl -sI http://localhost:4000
      echo ""
    ;;

    publish)
      git a . > /dev/null 2>&1 && sleep 1
      git c "push blog updates via SimpleCLI" > /dev/null 2>&1 && sleep 1
      git ps
    ;;

    help)
      jekyll_help
    ;;

    *)
      jekyll_help
    ;;
  esac
}
