#!/usr/bin/env bash
# Wrapper for ssllabs tool

function ssllabs_description(){
  echo "Perform SSLLabs scan; requires ssllabs-scan go application"
}

function ssllabs_help(){
  echo " "
  echo " Perform SSLLabs scan; requires ssllabs-scan go application"
  echo " "
  echo " USAGE: $(basename "$0") ssllabs <site>"
  echo " "
  echo " AVAILABLE SUBCOMMANDS:"
  echo " help     returns this message"
  echo " "
}

function ssllabs_handle(){
  command="$1"

  case "$command" in
    help)
      ssllabs_help
    ;;

    *)
    if [[ -z "${GOROOT}" || -z "${GOPATH}" ]]
    then
      echo-e "\nNo GO environment detected, exiting..."
    fi
    
    echo -e "\nThis may take a while if results are older than 12 hours..."
    ssllabs-scan-v3 -usecache -maxage 12 -grade "$1"
    ;;
 esac 
}

